# Generated by Django 5.0.7 on 2024-08-03 06:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expensesummary',
            unique_together={('user', 'category')},
        ),
    ]
