# Generated by Django 5.0.7 on 2024-08-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_expense_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
